export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const FETCH_SERVICES = 'FETCH_SERVICES';

export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const FETCH_VEHICLE = 'FETCH_VEHICLE';

export const FETCH_VEHICLE_SUCCESS = 'FETCH_VEHICLE_SUCCESS';

export const CREATE_VEHICLE = 'CREATE_VEHICLE';

export const CREATE_VEHICLE_SUCCESS = 'CREATE_VEHICLE_SUCCESS';

export const CREATE_VEHICLE_FAIL = 'CREATE_VEHICLE_FAIL';

export const DELETE_VEHICLE = 'DELETE_VEHICLE';

export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS';

export const DELETE_VEHICLE_FAIL = 'DELETE_VEHICLE_FAIL';

export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';

export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS';

export const UPDATE_VEHICLE_FAIL = 'UPDATE_VEHICLE_FAIL';
